/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'hairBands' : IDL.Null,
  'hairAccessories' : IDL.Null,
  'apparel' : IDL.Null,
  'jewelry' : IDL.Null,
  'scrunches' : IDL.Null,
  'earrings' : IDL.Null,
  'hairClips' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
  'image' : IDL.Text,
  'isNew' : IDL.Bool,
  'reviewCount' : IDL.Nat,
  'isBestSeller' : IDL.Bool,
  'priceCents' : IDL.Nat,
});
export const SeoSettings = IDL.Record({
  'metaDescription' : IDL.Text,
  'pageName' : IDL.Text,
  'keywords' : IDL.Text,
  'metaTitle' : IDL.Text,
  'ogTitle' : IDL.Text,
  'ogDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSeoSettings' : IDL.Func([], [IDL.Vec(SeoSettings)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getSeoSettings' : IDL.Func([IDL.Text], [IDL.Opt(SeoSettings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSeoSettings' : IDL.Func([SeoSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'hairBands' : IDL.Null,
    'hairAccessories' : IDL.Null,
    'apparel' : IDL.Null,
    'jewelry' : IDL.Null,
    'scrunches' : IDL.Null,
    'earrings' : IDL.Null,
    'hairClips' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
    'image' : IDL.Text,
    'isNew' : IDL.Bool,
    'reviewCount' : IDL.Nat,
    'isBestSeller' : IDL.Bool,
    'priceCents' : IDL.Nat,
  });
  const SeoSettings = IDL.Record({
    'metaDescription' : IDL.Text,
    'pageName' : IDL.Text,
    'keywords' : IDL.Text,
    'metaTitle' : IDL.Text,
    'ogTitle' : IDL.Text,
    'ogDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSeoSettings' : IDL.Func([], [IDL.Vec(SeoSettings)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSeoSettings' : IDL.Func([IDL.Text], [IDL.Opt(SeoSettings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSeoSettings' : IDL.Func([SeoSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };